Repository theforeman/puppet-pulp, pull requests merged in 2019-11, with the labels that each got.

#377 Update GHCG gem and drop rdoc
  Gemfile
Labels: Needs testing, Not yet reviewed, skip-changelog

#321 Add support for yum gpg_key_id and gpg_cmd parameters
  manifests/init.pp
  manifests/params.pp
  templates/yum_importer.json.erb
Labels: Needs testing, Not yet reviewed

#381 Add support for different CA certificates for apache and pulp
  manifests/apache.pp
  manifests/child/apache.pp
  manifests/init.pp
  manifests/params.pp
  spec/classes/pulp_apache_spec.rb
  spec/classes/pulp_child_apache_spec.rb
Labels: Enhancement, Needs testing
