Repository theforeman/puppet-pulp, pull requests merged in 2020-05, with the labels that each got.

#398 Modulesync: Require voxpupuli-test 1.4
  Gemfile
  Rakefile
  spec/spec_helper_acceptance.rb
Labels: Needs testing, Not yet reviewed

#399 Support puppet/extlib 5.x
  metadata.json
Labels: Needs testing

#402 Release 8.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, skip-changelog
